package com.gerermacoloc.app.domain;

public enum Rotation {
	NO_ROTATION,
	ROTATION_DAILY,
	ROTATION_WEEKLY,
	ROTATION_BIMONTHLY,
	ROTATION_MONTHLY,
	ROTATION_QUARTERLY,
	ROTATION_BIANNUAL,
	ROTATION_YEARLY
}
